apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-helloworld
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aspnet-helloworld
  template:
    metadata:
      labels:
        app: aspnet-helloworld
    spec:
      containers:
      - name: aspnet-app
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-helloworld-service
  namespace: default
spec:
  selector:
    app: aspnet-helloworld
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer