apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-ad-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet-ad-app
  template:
    metadata:
      labels:
        app: aspnet-ad-app
    spec:
      serviceAccountName: gmsa-service-account
      containers:
      - name: aspnet-ad-app
        image: mcr.microsoft.com/dotnet/sdk:8.0
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: AWS_REGION
          value: "ap-southeast-1"
        - name: SECRET_NAME
          value: "eks-gmsa-credentials"
        workingDir: /app
        command: ["/bin/bash"]
        args:
          - -c
          - |
            set -e
            echo "Copying source files..."
            cp /source/Program.cs /app/
            cp /source/aspnet-ldap.csproj /app/
            echo "Starting application..."
            dotnet run --urls http://0.0.0.0:8080
        volumeMounts:
        - name: source-code
          mountPath: /source
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
      volumes:
      - name: source-code
        configMap:
          name: aspnet-ldap-source
      nodeSelector:
        kubernetes.io/os: linux

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aspnet-ldap-source
  namespace: default
data:
  # ConfigMap created from external files: kubectl create configmap aspnet-ldap-source --from-file=sample-apps/aspnet-ldap/
---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-ad-service
  namespace: default
spec:
  selector:
    app: aspnet-ad-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer